spring.datasource.url: jdbc:mysql://localhost:3306/todolist?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: lHa?0QDojh
spring.jpa.hibernate.ddl-auto: none
